### PR TITLE
Bug-WDP190701-3

### PR DESCRIPTION
**Pull request by markal84**
- Feature box should have hover state
**fixed** by use @extended at hover state

- Feature box should be a link
**fixed** by add a element as a parent of .feature-box div

### CODE REVIEW

**Comment by Varenthein** [comment]
Am I wrong or you have here also commits from your previous task? Please let me know. 

It can be a result of starting new branch task from other previous branch task instead of master. **Always start from master**.

**Comment by Varenthein** [comment]
You removed the question label, but where is the answer? :D I've really asked a question ;)

**Comment by markal84** [comment]
I'm still a little confused about this PR so please check if I done it correctly this time. Thanks !

**Comment by Varenthein** [comment]
It look okay.

**Pull request merged**
